version: '3.8'

services:
  # Backend - FastAPI service
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/astrology_db
    depends_on:
      - postgres

  # Frontend - Next.js service
  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - BACKEND_API_URL=http://backend:8000

  # PostgreSQL Database Service
  postgres:
    image: postgres:15
    container_name: astrology-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Change this for production
      POSTGRES_DB: astrology_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

volumes:
  postgres_data:
