version: '3.9'

services:
  backend:
    ports:
      - "9001:9000"  # Custom dev port for backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True

  frontend:
    ports:
      - "3002:3001"  # Custom dev port for frontend
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9001/api

  db:
    ports:
      - "5434:5432"  # Custom port for local database
